packages:
  - 'packages/i18n-tracker'
  - 'packages/js-api-generator'
  - 'packages/config-generator'
  - 'packages/cli-generator'
  - 'packages/tauri-typedoc-theme'
  - 'packages/releases-generator'
  - 'packages/compatibility-table'
